// <auto-generated />
using System;
using EmployeeDemo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeDemo.Database.Migrations
{
    [DbContext(typeof(EmployeeDemoDbContext))]
    [Migration("20230419040427_Add Supervisors Table")]
    partial class AddSupervisorsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeDemo.Database.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4061),
                            FirstName = "Dax",
                            LastName = "Mcclellan",
                            MiddleName = "Kipton"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4116),
                            FirstName = "Carter",
                            LastName = "Merritt",
                            MiddleName = "Konnor"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4119),
                            FirstName = "Finnian",
                            LastName = "Raymond",
                            MiddleName = "Gianluca"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4121),
                            FirstName = "Sara",
                            LastName = "Stanton",
                            MiddleName = "Leilany"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4124),
                            FirstName = "Darion",
                            LastName = "Fournier",
                            MiddleName = "Zavion"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4127),
                            FirstName = "Charlee",
                            LastName = "Lake",
                            MiddleName = "Leilany"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4129),
                            FirstName = "Dario",
                            LastName = "Durham",
                            MiddleName = "Reese"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4132),
                            FirstName = "Kyron",
                            LastName = "Messer",
                            MiddleName = "Sterling"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4135),
                            FirstName = "Alek",
                            LastName = "White",
                            MiddleName = "Jakoby"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4138),
                            FirstName = "Kenna",
                            LastName = "Mccarty",
                            MiddleName = "Janely"
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4140),
                            FirstName = "Kassandra",
                            LastName = "Drake",
                            MiddleName = "Dulce"
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4143),
                            FirstName = "Jackson",
                            LastName = "Salgado",
                            MiddleName = "Nova"
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4145),
                            FirstName = "Hasan",
                            LastName = "Meyer",
                            MiddleName = "Elias"
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4148),
                            FirstName = "Rosemary",
                            LastName = "Yeager",
                            MiddleName = "Camryn"
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4151),
                            FirstName = "Dominic",
                            LastName = "Mccarty",
                            MiddleName = "Gilberto"
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4153),
                            FirstName = "Katarina",
                            LastName = "Crosby",
                            MiddleName = "Dalia"
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4156),
                            FirstName = "Wren",
                            LastName = "Parsons",
                            MiddleName = "Linda"
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4158),
                            FirstName = "Julie",
                            LastName = "Preston",
                            MiddleName = "Ansley"
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4161),
                            FirstName = "Tyce",
                            LastName = "Hackett",
                            MiddleName = "Zaine"
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4164),
                            FirstName = "Kaiden",
                            LastName = "Simpson",
                            MiddleName = "Josiah"
                        },
                        new
                        {
                            Id = 21,
                            DateOfBirth = new DateTime(2023, 4, 18, 23, 4, 27, 40, DateTimeKind.Local).AddTicks(4167),
                            FirstName = "Trae",
                            LastName = "Lehman",
                            MiddleName = "Elliott"
                        });
                });

            modelBuilder.Entity("EmployeeDemo.Database.Models.Supervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Supervisors");
                });
#pragma warning restore 612, 618
        }
    }
}
