// <auto-generated />
using System;
using EmployeeDemo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeDemo.Database.Migrations
{
    [DbContext(typeof(EmployeeDemoDbContext))]
    partial class EmployeeDemoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeDemo.Database.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupervisorId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Dax",
                            LastName = "Mcclellan",
                            MiddleName = "Kipton",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Carter",
                            LastName = "Merritt",
                            MiddleName = "Konnor",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Finnian",
                            LastName = "Raymond",
                            MiddleName = "Gianluca",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Sara",
                            LastName = "Stanton",
                            MiddleName = "Leilany",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Darion",
                            LastName = "Fournier",
                            MiddleName = "Zavion",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Charlee",
                            LastName = "Lake",
                            MiddleName = "Leilany",
                            SupervisorId = 2
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Dario",
                            LastName = "Durham",
                            MiddleName = "Reese",
                            SupervisorId = 2
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Kyron",
                            LastName = "Messer",
                            MiddleName = "Sterling",
                            SupervisorId = 2
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Alek",
                            LastName = "White",
                            MiddleName = "Jakoby",
                            SupervisorId = 2
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Kenna",
                            LastName = "Mccarty",
                            MiddleName = "Janely",
                            SupervisorId = 2
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Kassandra",
                            LastName = "Drake",
                            MiddleName = "Dulce",
                            SupervisorId = 3
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Jackson",
                            LastName = "Salgado",
                            MiddleName = "Nova",
                            SupervisorId = 3
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Hasan",
                            LastName = "Meyer",
                            MiddleName = "Elias",
                            SupervisorId = 3
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Rosemary",
                            LastName = "Yeager",
                            MiddleName = "Camryn",
                            SupervisorId = 3
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Dominic",
                            LastName = "Mccarty",
                            MiddleName = "Gilberto",
                            SupervisorId = 3
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Katarina",
                            LastName = "Crosby",
                            MiddleName = "Dalia",
                            SupervisorId = 4
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Wren",
                            LastName = "Parsons",
                            MiddleName = "Linda",
                            SupervisorId = 4
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Julie",
                            LastName = "Preston",
                            MiddleName = "Ansley",
                            SupervisorId = 4
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Tyce",
                            LastName = "Hackett",
                            MiddleName = "Zaine",
                            SupervisorId = 4
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Kaiden",
                            LastName = "Simpson",
                            MiddleName = "Josiah",
                            SupervisorId = 4
                        },
                        new
                        {
                            Id = 21,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Trae",
                            LastName = "Lehman",
                            MiddleName = "Elliott",
                            SupervisorId = 5
                        });
                });

            modelBuilder.Entity("EmployeeDemo.Database.Models.Supervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Supervisors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Jameson",
                            LastName = "Bruce",
                            MiddleName = "Bear"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Sammie",
                            LastName = "Kaylee",
                            MiddleName = "Catherin"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Vinal",
                            LastName = "Gabe",
                            MiddleName = "Jerrod"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Carissa",
                            LastName = "Austen",
                            MiddleName = "Novalee"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2023, 4, 19, 9, 45, 52, 530, DateTimeKind.Local),
                            FirstName = "Brady",
                            LastName = "Micah",
                            MiddleName = "Fay"
                        });
                });

            modelBuilder.Entity("EmployeeDemo.Database.Models.Employee", b =>
                {
                    b.HasOne("EmployeeDemo.Database.Models.Supervisor", "Supervisor")
                        .WithMany("Employees")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("EmployeeDemo.Database.Models.Supervisor", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
